spring.application.name=SpringEcom

spring.datasource.url=jdbc:postgresql://localhost:5432/product
spring.datasource.username=postgres
spring.datasource.password=Admin66@@55@@

spring.jpa.hibernate.ddl-auto=update
